services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pokemon-in-home
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    entrypoint:
      - "flyway"
      - "-url=jdbc:postgresql://postgres:5432/pokemon-in-home"
      - "-user=postgres"
      - "-password=supersecretpassword"
      - "-baselineOnMigrate=true"
      - "migrate"
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

volumes:
  postgres_data:
  redis_data: