services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pokemon-in-home'
      - 'POSTGRES_PASSWORD=supersecretpassword'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
